export const Constants = {
  /* These constants are populated by variables in .env, then set by Webpack */
  STANDARD_DOMAIN_LIST: STANDARD_DOMAIN_LIST.split(','),
  STANDARD_BSKY_DOMAIN_LIST: STANDARD_BSKY_DOMAIN_LIST.split(','),
  DIRECT_MEDIA_DOMAINS: DIRECT_MEDIA_DOMAINS.split(','),
  TEXT_ONLY_DOMAINS: TEXT_ONLY_DOMAINS.split(','),
  INSTANT_VIEW_DOMAINS: INSTANT_VIEW_DOMAINS.split(','),
  GALLERY_DOMAINS: GALLERY_DOMAINS.split(','),
  FORCE_MOSAIC_DOMAINS: FORCE_MOSAIC_DOMAINS.split(','),
  OLD_EMBED_DOMAINS: OLD_EMBED_DOMAINS.split(','),
  MOSAIC_DOMAIN_LIST: MOSAIC_DOMAIN_LIST.split(','),
  MOSAIC_BSKY_DOMAIN_LIST: MOSAIC_BSKY_DOMAIN_LIST.split(','),
  POLYGLOT_DOMAIN_LIST: POLYGLOT_DOMAIN_LIST.split(','),
  POLYGLOT_ACCESS_TOKEN: POLYGLOT_ACCESS_TOKEN,
  API_HOST_LIST: API_HOST_LIST.split(','),
  API_HOST_ROOT: `https://${API_HOST_LIST.split(',')[0]}`,
  RELEASE_NAME: RELEASE_NAME,
  GIF_TRANSCODE_DOMAIN_LIST: GIF_TRANSCODE_DOMAIN_LIST.split(','),
  API_DOCS_URL: `https://github.com/FxEmbed/FxEmbed/wiki/API-Home`,
  TWITTER_ROOT: 'https://x.com',
  TWITTER_GLOBAL_NAME_ROOT: 'x.com',
  TWITTER_API_ROOT: 'https://api.x.com',
  TWITTER_VIDEO_BASE: 'https://video.twimg.com',
  BSKY_ROOT: 'https://bsky.app',
  BSKY_VIDEO_BASE: 'https://video.bsky.app',
  BSKY_API_ROOT: 'https://public.api.bsky.app',
  BOT_UA_REGEX:
    /bot|facebook|embed|got|firefox\/92|firefox\/38|curl|wget|go-http|yahoo|generator|whatsapp|revoltchat|preview|link|proxy|vkshare|images|analyzer|index|crawl|spider|python|node|mastodon|http\.rb|ruby|bun\/|fiddler|iframely|steamchaturllookup|bluesky|matrix-media-repo|cardyb|resolver|util/gi,
  /* 3 hours */
  GUEST_TOKEN_MAX_AGE: 3 * 60 * 60,
  GUEST_BEARER_TOKEN: `Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA`,
  GUEST_FETCH_PARAMETERS: [
    'cards_platform=Web-12',
    'include_cards=1',
    'include_ext_alt_text=true',
    'include_ext_views=true',
    'include_quote_count=true',
    'include_reply_count=1',
    'tweet_mode=extended',
    'include_entities=true',
    'include_ext_media_color=true',
    'include_ext_media_availability=true',
    'include_ext_sensitive_media_warning=true',
    'include_ext_has_birdwatch_notes=true',
    'simple_quoted_tweet=true',
    'ext=mediaStats%2ChighlightedLabel'
  ].join('&'),
  BASE_HEADERS: {
    'DNT': `1`,
    'x-twitter-client-language': `en`,
    'sec-ch-ua-mobile': `?0`,
    'content-type': `application/json`,
    'cache-control': `no-cache`,
    'x-twitter-active-user': `yes`,
    'sec-ch-ua-platform': `"Windows"`,
    'Accept': `*/*`,
    'Origin': `https://x.com`,
    'Sec-Fetch-Site': `same-site`,
    'Sec-Fetch-Mode': `cors`,
    'Sec-Fetch-Dest': `empty`,
    'Sec-Gpc': `1`,
    'Permissions-Policy': `browsing-topics=()`,
    'Pragma': `no-cache`,
    'Referer': `https://x.com/home`,
    'Accept-Encoding': `gzip, deflate, br, zstd`,
    'Accept-Language': `en`
  },
  RESPONSE_HEADERS: {
    'allow': 'OPTIONS, GET, PURGE, HEAD',
    'content-type': 'text/html;charset=UTF-8',
    'x-powered-by': `${RELEASE_NAME}`,
    'x-trans-rights': 'true',
    'Vary': 'Accept-Encoding, User-Agent'
  },
  API_RESPONSE_HEADERS: {
    'access-control-allow-origin': '*',
    'content-type': 'application/json'
  },
  POLL_TWEET_CACHE: 'max-age=60',
  DEFAULT_COLOR: '#10A3FF',
  FRIENDLY_USER_AGENT: `Mozilla/5.0 FxEmbedBot/2.0 (like Twitterbot; +https://fxembed.com/crawler)`
};
